### PR TITLE
Add basic tagged flashcards to parser-generator

### PR DESCRIPTION
**Pull request by ivyraine**
This is a WIP implementation of #151. It is actively being worked on, after having had a busy week prior. Feedback is encouraged, especially with regard to the grammar.

### CODE REVIEW

**Comment by reuseman** [comment]
Hey @ivyraine nice that you started to figure out how OHM works. I've just seen the PR, but I did not see in depth the content. The only catch is that you requested to merge with the main branch, but it should be with the "ohm" one.  

Moreover, I would love that in the rewrite it's clear the distinction between the flashcards in the Obsidian editor, the different type of cards, the cards in Anki. This is just something to keep in mind as a goal.

In the next days I am going to see better the PR, but just from a quick overview it seems great. It would be nice if on parallel we can define the test suite as well (#152) in order to define test cases for all the old and new issues.

**Comment by ivyraine** [comment]
@reuseman The `ohm` branch is missing much of the project. Do you intend to re-write the project from the ground-up?

**Comment by ivyraine** [comment]
I think there needs to be a better source of truth for what the re-write should look like and include. Perhaps we could create a Discussion?

**Comment by reuseman** [comment]
@ivyraine the idea was to have a clean sandbox where trials just on OHM parsing can be made. But indeed we can just fork out from the current branch and iterate over it.

**Pull request closed without merging**
